name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2
      - name: Build wheels
        run: cibuildwheel --output-dir dist
      - uses: actions/upload-artifact@v4
        with:
          name: grpoptim-wheels-${{ matrix.os }}
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: grpoptim-wheels-macos-latest
          path: dist/macos
      - uses: actions/download-artifact@v4
        with:
          name: grpoptim-wheels-ubuntu-latest
          path: dist/linux
      - uses: actions/download-artifact@v4
        with:
          name: grpoptim-wheels-windows-latest
          path: dist/windows
      - name: Combine artifacts
        run: |
          mkdir -p dist
          cp dist/macos/* dist/
          cp dist/linux/* dist/
          cp dist/windows/* dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/